#!/bin/bash
#mis on maas? enam kui 1h pole infot tulnud
#parameetreid pole vaja, viimase state seisu AVV alusel
#26.07.2012


cd /srv/scada/bin
TMP=bndownreport.tmp
TMP2=bndownreport.tmp2

cat /dev/null > $TMP
cat /dev/null > $TMP2

echo Oota...

./bnfind UPV | cut -d"|" -f1,2,5,7,8 | sed 's/ /_/g' >> $TMP  # 4 liiget LIST sisse 

#cat $TMP # ajutine


for LINE in `cat $TMP`; do # summeerida liiklusmahud
    #echo "LINE ${LINE}" # ajutine
    
    age=`echo "$LINE" | cut -d"|" -f5`  # sekundites vanus
    
   #echo age $age LINE $LINE # ajutine

    if [ ! "$age" =  "" ]; then
        if [ $age -gt 3600 ]; then # vist numbrid koik olemas, ainult varsked (1h max)
            echo "$age $LINE" >> $TMP2 
        fi
    fi
done


# sortida summeeeritud liiklusmahud ja naidata read

cat $TMP2 | sort -nk1 | more 
