#!/bin/bash
#loeme newstate tabelisse sql kujul setupi 

if [ "$1" = "" ]; then
    echo anna parameetriks mac voi ka mitu...; sleep 1; exit 1
fi

#shift; 
echo "${*}" # koik macid mis parameetriteks anti


echo; echo -n "anna laiendita sql failinimi (kataloogis /srv/scada/conf): "; read filename
if [ "$filename" = "" ]; then
    echo "?"; exit 1
fi

echo; echo -n "anna muutujad ylekysimiseks: "; read registers # eraldajaks tyhik, neid kysitakse igas tsyklis
if [ ! "$registers" = "" ]; then
    echo "varieeruvad muutujad: ${registers}" # kuni 4 registrit
    reg1=`echo "${registers}" | cut -d" " -f1` 
    reg2=`echo "${registers}" | cut -d" " -f2` 
    if [ "$reg2" = "$reg1" ]; then reg2=" "; reg3=" "; reg4=" "; fi
    reg3=`echo "${registers}" | cut -d" " -f3` 
    if [ "$reg3" = "" ]; then reg3=" "; reg4=" "; fi
    reg4=`echo "${registers}" | cut -d" " -f4` 
    if [ "$reg4" = "" ]; then reg4=" "; fi
fi

cd /srv/scada/conf


for mac in `echo "${*}"`
do
    if [ `echo $mac | wc -c` -eq 12 ]; then 
        echo invalid mac $mac; exit 1
    else
        echo mac $mac
    fi
    
    
    
    if [ -f ${filename}.sql ]; then 
        if [ ! "$reg1" = " " ]; then echo -n "register ${reg1}:"; read val1; fi
        if [ ! "$reg2" = " " ]; then echo -n "register ${reg2}:"; read val2; fi
        if [ ! "$reg3" = " " ]; then echo -n "register ${reg3}:"; read val3; fi
        if [ ! "$reg4" = " " ]; then echo -n "register ${reg4}:"; read val4; fi
        
        cmd=".read ${filename}.sql"
        cat ${filename}.sql | sed "s/XXXXXXXXXXXX/${mac}/g" | grep -v "^${reg1} | grep -v "^${reg2} | grep -v "^${reg3} | grep -v "^${reg4} > lastload.sql   
        # eespool sed juures kasuta jutumarke ", mitte ' !!!! muidu ei asenda!
        
        # nyyd tekitame uued laused muudetud parameetritega
        if [ ! "$reg1" = " " ]; then echo "insert into newstate(mac,register,value) values('${mac}','${reg1}','${val1}');" >> lastload.sql; fi
        if [ ! "$reg2" = " " ]; then echo "insert into newstate(mac,register,value) values('${mac}','${reg2}','${val2}');" >> lastload.sql; fi
        if [ ! "$reg3" = " " ]; then echo "insert into newstate(mac,register,value) values('${mac}','${reg3}','${val3}');" >> lastload.sql; fi
        if [ ! "$reg4" = " " ]; then echo "insert into newstate(mac,register,value) values('${mac}','${reg4}','${val4}');" >> lastload.sql; fi
        #varieeritud muutujad jaavad loppu
    else
        beep; echo "faili /srv/scada/conf/${filename}.sql ei leitud!" ; exit 1
    fi

    
done
echo " kontrolli tulemust /srv/scada/conf/lastload.sql"; sleep 1
more lastload.sql

echo "kui fail vajab editeerimist, katkesta. setupiga jatkamiseks enter:"; read n

echo ".read lastload.sql" | sqlite3 /srv/scada/sqlite/monitor

/srv/scada/bin/bnqueue
exit 0
