#!/bin/bash
#saadan parameetriks antud tunnusele vastavale kontrolleeritele $2 cmd $3 sisuga
#kaivitatava kasu esimene parameeter on bnmulti tulemus
# lubatud 2 parameetrit nagu ka bnloc jaoks ning kolmas otsinguks
# aga neid ei pea andma, otsitakse exe parameetrit


SILENCE=1; export SILENCE  # bnsend jaoks et entereid ei nouaks
par1=""; par2=""; par3=""; fork=0

if [ "$1" = "-f" ]; then # fork subprocesses
    fork=1; echo subprocesses will be forked...; shift
fi

par1=$1
echo bnloc par1 $par1

if [ ! -x $2 ]; then
    par2=$2; echo bnloc par2 $par2; shift
fi

if [ ! -x $2 ]; then
    par3=$2; echo bnloc par3 $par3; shift
fi

if [ ! -x $2 ]; then
    echo parameter error... exit 1
else
    echo executing $2 mac $3 $4 for every mac
fi

#./bnloc $par1 $par2 $par3 | grep -v test | cut -d"|" -f1 # ajutine

for mac in `./bnloc $par1 $par2 $par3 | grep -v test | cut -d"|" -f1`; do
 #  echo "mac ${mac} "
   if [ $fork -eq 0 ]; then #tavaline kasutamine
        $2 $mac "${3}" $4 #| grep $3
   else
        nohup $2 $mac "${3}" $4 > $mac.out & # see ei taha toimida, vahemalt bnstate korral
        sleep 5
        cat $mac.out
   fi
done


