#!/bin/bash
# barionet kontrollerite updatemise script bnupdate.sh

#28.06.2012 vaikne toimimine -q, et at abil saaks kaivitada. siis on noutav BNVER! html uuendamist ei tee.
# sama tulemuse annab par3 quiet, muidu ei saa bnmulti kaudu teha


#17.11.2011 lisasin kogu ajax kataloogi sisu kopeerimise vaid html asemel, et css jms ka laheks kaasa

#parameetriteks vaja update kask kujul mac "update1:SIZE,SUM update4:SIZE,SUM update6:SIZE,SUM" 
# koiki parameetreid ei pea andma, eduka lopu korral jouab ise norm tooreziimi (barionet)

# paneb rescue mode (S100:bnrescue, cmd:REBOOT)
# kontrollib mis on ver sees - bnrescue?

# kui on, siis teeb upload etteantud WEBx (uploadx:size,sum)
# kui edukas, siis tagasi normaalsesse moodi (S100:barionet, cmd:REBOOT)

#kontrollib ka kas on olemas /var/www/<mac>/*.html setup jaoks - ehk voiks ka cob siin olla?
# ja lubab seal sees olevaid faile uuendada



newstate() {  # kirjutame newstate tabelisse register value
register=$1
value=$2
cmd="insert into newstate(mac,register,value) values('${mac}','${register}','${value}');"
resp=`echo -e ".timeout ${TOUT}\n${cmd}" | sqlite3 /srv/scada/sqlite/monitor`

if [ "$resp" = "" ]; then
    echo newstate salvestamine onnestus | tee -a $LOG
else
    beep; beep; echo miski jama newstate salvestamisega | tee -a $LOG; echo $resp
    exit 1
fi

  
    
TS=`date +%s`
TSOUT=`expr $TS + $TOUT2` 
#echo TS $TS TSOUT $TSOUT
echo "ootame kuni newstate tabelist kaob ${register}:${value}..." | tee -a $LOG
while [ $TS -lt $TSOUT ]; do
    sleep 10 ; echo -n "."
    TS=`date +%s`
    cmd="select value from newstate where mac='${mac}' and register='${register}';"
    resp=`echo -e ".timeout ${TOUT}\n${cmd}" | sqlite3 /srv/scada/sqlite/monitor`
    #echo $cmd; echo $resp
    if [ "$resp" = "" ]; then # asi korras 
        TS=$TSOUT
        OK=1
    fi
done

if [ $OK -eq 1 ]; then
    echo "newstate registrist kadunud ${register}:${value}! jatkame..." | tee -a $LOG; sleep 1
else
    echo "newstate registrisse jai alles ${register}:${value} 20 min jooksul! katkestame..." | tee -a $LOG; sleep 1
    exit 1
fi

}





statewait() {  # ootame kas ilmub soovitud register value muu jura hulka
register=$1
value=$2

TS=`date +%s`
TSOUT=`expr $TS + $TOUT2` 
#echo TS $TS TSOUT $TSOUT
echo "ootame kuni state tabelisse ilmub ${register} sisusse muuhulgas ${value}..." | tee -a $LOG
while [ $TS -lt $TSOUT ]; do
    sleep 10 ; echo -n "."
    TS=`date +%s`
    cmd="select value from state where mac='${mac}' and register='${register}' and timestamp>${TS}-5;"
    resp=`echo -e ".timeout ${TOUT}\n${cmd}" | sqlite3 /srv/scada/sqlite/monitor`
    #echo $cmd ; echo $resp
    if [ `echo "${resp}" | grep "${value}" | wc -l` -gt 0 ]; then # asi korras, ilmus 
        TS=$TSOUT
        OK=1
    else
        echo $resp # voime saada bad OK asemel ja siis voiks katkestada...
    fi
done

if [ $OK -eq 1 ]; then
    echo "state registrist leitud ${register}:${value}! jatkame..." | tee -a $LOG; sleep 1
else
    echo "state registrisse ei saabunud ${register} sisusse ${value} 20 min jooksul! katkestame..." | tee -a $LOG; sleep 1
    exit 1
fi

}







#### MAIN  #########################

echo; echo $* # debug jaoks
beep; sleep 3

TOUT=2000 # ms sqlite baasile timeout
TOUT2=3600 # s kontrolleri viimase paketi vanus

TS=`date +%s`
LOG=/srv/scada/logs/bnupdate
(echo -n $LOGNAME $*; date) >> $LOG

parex="parameetriteks <mac> \"<updatex:size,sum> <updatex:size,sum> <updatex:size,sum>\""

if [ "$1" = "-q" ]; then
    quiet=1; shift  #vaikne ja html uuendamiseta
    echo vaikne taitmine...
else
    quiet=0 #tavaline interaktiivne
fi

if [ "$BNVER" = "" ]; then
    if [ $quiet -eq 1 ]; then
        echo katkestame $0 quiet mode kaivituse sest BNVER on puudu
        exit 1
    fi
    
    echo "env muutuja BNVER$ on vajalik, mis on APVER$ (voib ka koos kuupaevaga, kui muidu vahet ei tee - ntx eccua1009 10.10.2009"
    echo " aga kui on plaanis setup html uuendada, siis anna env muutujaks ainult katalooginimi!"
    beep
    echo -n "anna BNVER vaartus: "; read BNVER; export BNVER
else
    echo "APVER$ kuhu joudma peame on ${BNVER}..."
    (echo -n "APVER$ kuhu joudma peame on ${BNVER}..."; date) >> $LOG
    sleep 2
fi

if [ "$3" = "quiet" ]; then # vaikne
    echo vaikne taitmine... 
    quiet=1
fi

if [ "$2" = "" ]; then # "register:value [register:value]"
    echo parameeter 2 puudub... 
    echo $parex;  beep; usleep 100000; beep; sleep 1; exit 1
fi

for pair in `echo "${2}"`
do
    echo $pair
    if [ `echo $pair | grep update | wc -l` -lt 1 ]; then
        echo vale cmd; exit 1
    fi 
done

if [ ! `echo -n $1 | wc -c` -eq 12 ]; then
    echo "vale mac ${1} pikkus, katkestame..."
    echo $parex;  beep; usleep 100000; beep; sleep 1; exit 1
fi

(echo -n "*** mac ${1} teha ${2} "; date) | tee -a $LOG; sleep 1
mac=$1

if [ ! -d /var/www/${mac} ]; then
    beep; echo "kataloog /var/www/${mac}/ puudub, kas teeme (y/n)?: "; read n
    if [ "$n" = "y" ]; then
        mkdir /var/www/${mac}
        chown www-data /var/www/${mac}
        chgrp nagios /var/www/${mac}
    else
        echo katkestame siis...| tee -a $LOG; sleep 1; exit 1
    fi
fi
        
cd /var/www/${mac}; echo -n "asume "; pwd


if [ -f uiappsetup1.html -a -f uisystem.html ]; then # vahemalt uiappsetup1 ja uisystem.html on olemas
    ls -l *.html | tee -a $LOG
else
    echo "html setup fail puudub kataloogist /var/www/${mac}!"
    ls -l *.html
fi


beep

if [ $quiet -eq 0 ]; then
    echo -n "kas tekitame/uuendame setup faile (y/n)?: "; read n
    if [ "$n" = "y" ]; then
        scp root@server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/${BNVER}/BCL/uia*.html . # voimalik ka uiappsetup2.html vms
        scp root@server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/rescue/BCL/uisystem.html .
        scp root@server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/${BNVER}/ajax/uia*.html .
        chown www-data *
        chgrp nagios *
        ls -l | tee -a $LOG
        echo -n anna enter...; read n # sleep 4
    else
        echo jatkame setup failide uuenduseta | tee -a $LOG; sleep 1
    fi
fi


# setup failid olemas

#beep

#kontrollime kas bnrescue on ikka olemas kontrolleris
cd /srv/scada/bin

tokok=`/srv/scada/bin/bnstate $mac tok | grep bnrescue | wc -l`
if [ ! $tokok -eq 1 ]; then
    echo ei saa update teha sest bnrescue puudu kontrollerist...
    /srv/scada/bin  /bnstate $mac tok
    exit 1
fi

sleep 1
echo alustame suhtlust kontrolleriga...
#sleep 5

#exit 0 # ajutine


# kas kontroller on elus?

#cmd="select max(timestamp) from id_log where mac='${mac}';"
#resp=`echo -e ".timeout ${TOUT}\n${cmd}" | sqlite3 /srv/scada/sqlite/id_log`

#echo $resp
#VALTIME=`echo $resp | cut -d"." -f1`
#HUMTIME=`date -d "1970-01-01 UTC ${VALTIME} seconds" +"%d.%m %H:%M"`
#VANUS=`expr $TS - $VALTIME`
#OK=0 # edu lipp 

#if [ $VANUS -gt 1200 ]; then # liiga vana
    #echo "side puudub ${VANUS} s jooksul, viimane teade kontrollerist ${mac} saabus ${HUMTIME}" | tee -a $LOG
    #beep; usleep 100000; beep; exit 1
#fi

# side on olemas, mis on S100 sees? paneme bnrescue kui juba ei ole.
echo "oletame, et side ok, APVER$ kuhu joudma peame on ${BNVER}..." | tee -a $LOG

cmd="select value from state where mac='${mac}' and register='S100';"
resp=`echo -e ".timeout ${TOUT}\n${cmd}" | sqlite3 /srv/scada/sqlite/monitor`

if [ "$resp" = "bnrescue" ]; then
    echo "kontrolleri seadistusparameeter S100 on juba bnrescue..." | tee -a $LOG
else
    echo "paneme newstate tabelisse S100:bnrescue"
    newstate S100 bnrescue  # LAS MUUDAB SETUPPI
fi    

cmd="select value from state where mac='${mac}' and register='ver';"
resp=`echo -e ".timeout ${TOUT}\n${cmd}" | sqlite3 /srv/scada/sqlite/monitor`
#echo $cmd
#echo $resp

if [ `echo $resp | grep rescue | wc -l` -gt 0 ]; then
    #echo "kontroller juba tootab rescue modes..."
    echo "kontroller juba tootab rescue modes..." | tee -a  $LOG
else
    #echo teeme reboodi et rescue moodi saada...
    echo teeme reboodi et rescue moodi saada... | tee -a  $LOG
    newstate cmd REBOOT
    statewait ver rescue  # ootame kuni ilmub
fi    


#nyyd oleme  rescue modes, saadame uue softi vms mis $2 ette naeb

for keyvalue in `echo "${2}"`; do
    echo keyvalue $keyvalue; sleep 1
    if [ ! `echo $keyvalue | grep ":" | wc -l` -eq 1 ]; then
        echo "vigane register:value ${keyvalue}! katkestame..." | tee -s $LOG
         beep; usleep 100000; beep; exit 1
    fi
    key=`echo $keyvalue | cut -d":" -f1` 
    key2=`echo $key | cut -c1-6`
    echo key $key key2 $key2
#    if [ ! `echo "$key2" | grep "update" | wc -l` -gt 0 -a ! "$key" = "cmd" -a ! "$key" = "S100" ]; then
#        echo "lubamatu register ${key}! katkestame..." | tee -a $LOG
#         beep; usleep 100000; beep; exit 1
#    fi
    value=`echo $keyvalue | cut -d":" -f2`
    newstate $key $value # saadame newstate tabelisse mis vaja kujul S100 bnrescue vms
    statewait ERV "${key} OK" # env muutujas peab sisalduma "updateX OK", kus X on 1...7   
done

echo "nyyd S100:barionet" | tee -a $LOG

newstate S100 barionet
echo Ootame...
statewait S100 barionet



newstate cmd REBOOT

#echo "state tabelisse peab AVV kontrolleri $mac kohta ilmuma ver sisusse ${BNVER}, ootame..."

statewait ver "${BNVER}" # uuematel softidel on AVV mitte ver!
(echo -n "mac ${mac} updatemise edukas lopp "; date) | tee -a $LOG     
(echo -n "${mac} update ${BNVER} ${2} "; date) >> ${LOG}.oklist    
#echo kontrolleri mac $mac update edukas lopp
beep; usleep 500000; beep; usleep 500000; beep; exit 0


 
