#!/bin/bash
#liiklusmahud UTW raporteerida. 4 liikme summa.
#parameetreid pole vaja, viimase state seisu alusel kuu algusest annab. kas vanust kontrollida?
#26.07.2012
#peaks naitama vaid neid, mis on varsked. tahame ju jooksva kuu kohta... state aja alusel.


cd /srv/scada/bin
TMP=bnUTWreport.tmp
TMP2=bnUTWreport.tmp2

cat /dev/null > $TMP
cat /dev/null > $TMP2

echo Oota...

./bnfind UTW | cut -d"|" -f1,2,5,7,8 | sed 's/ /_/g' >> $TMP  # 4 liiget LIST sisse 

#cat $TMP # ajutine


for LINE in `cat $TMP`; do # summeerida liiklusmahud
    #echo "LINE ${LINE}" # ajutine
    utw1=0; utw2=0; utw3=0; utw4=0; LINESUM=0
    
    utw1=`echo "$LINE" | cut -d"|" -f4 | cut -d"_" -f1`  # udp in
    utw2=`echo "$LINE" | cut -d"|" -f4 | cut -d"_" -f2`  # udp out
    utw3=`echo "$LINE" | cut -d"|" -f4 | cut -d"_" -f3`  # tcp in
    utw4=`echo "$LINE" | cut -d"|" -f4 | cut -d"_" -f4`  # tcp out
    age=`echo "$LINE" | cut -d"|" -f5 `  # sekundites vanus
    
    if [ ! "$utw1" = "" -a ! "$utw2" = "" -a ! "$utw3" = "" -a ! "$utw4" = "" -a $age -lt 86400 ]; then # vist numbrid koik olemas, ainult varsked (24h max)
        LINESUM=`expr $utw1 + $utw2 + $utw3 + $utw4`
        echo "$LINESUM $LINE" >> $TMP2 
    fi
    
    #echo LINESUM $LINESUM utwX $utw1 $utw2 $utw3 $utw4 age $age # ajutine
    
done


# sortida summeeeritud liiklusmahud ja naidata read

cat $TMP2 | sort -nrk1 | more 
