#!/bin/bash
#lingime hostid softikataloogidesse
#jun 2012
#LIST="00204ACA817F 00204ACC60B2 00204ACA8483 00204ACC602F 00204ACC5D1E 00204ACC5D96 00204ADE1A52 00204ADEA859 00204ADEA839 00204ADEAB91 00204ADEA8CA 00204ADEAC52 00204ACC39A1 00204ADEADE5 00204ADE0DBA 00204ADEA812"

#parameetriks kataloog ja fail, nt eccua_v3/web4.cob


LIST=`cat`
for mac in `echo "$LIST"`
do
    if [ -d $mac ]; then
        #echo $mac directory...
        ls -l $mac/*.cob | cut -d" " -f5-
    else
        echo NO directory $mac...
    fi
    echo
    #sleep 2 #; echo
done
