#!/bin/bash
#lingime hostid softikataloogidesse
# EI SAA symlinkida, apache ei anna faili katte!! hardlink voib olla!
# esialgu siisi hardlink, aga parast teeme nii et kontrollerile saab oelda kust fail votta...
#kas hardlink sailub peale eeskuju uuendamist?

#jun 2012
#LIST="00204ACA817F 00204ACC60B2 00204ACA8483 00204ACC602F 00204ACC5D1E 00204ACC5D96 00204ADE1A52 00204ADEA859 00204ADEA839 00204ADEAB91 00204ADEA8CA 00204ADEAC52 00204ACC39A1 00204ADEADE5 00204ADE0DBA 00204ADEA812"

#parameetriks kataloog ja fail, nt eccua_v3/web4.cob


if [ "$1" = "" ]; then
    echo parameter for development directory and file needed; sleep 1; exit 1
fi

if [ ! -f $1 ]; then
    echo "directory/file $1 missing!"; sleep 1; exit 1
fi

file=`echo $1 | cut -d "/" -f2`

LIST=`cat`
for mac in `echo "$LIST"`
do
    if [ -d $mac ]; then
        echo $mac hardlinking $file...
        rm -f ${mac}/${file}; ln $1 ${mac}/${file}; ls -l $mac/*.cob | cut -c32-
    else
        echo directory $mac creating and linking $file...
        mkdir $mac #; chown witvilla $mac; chgrp witvilla $mac
        ln $1 ${mac}/${file}; ls -l $mac/*.cob | cut -c32-
    fi
    chown -R witvilla $mac; chgrp -R witvilla $mac
    (echo -n "${mac}/${file}"; date) >> ${mac}/update.log
    ls -l ${mac}/${file} >> ${mac}/update.log
done
