#!/bin/bash


if [ "$3" = "" ]; then
   echo " anna parameetriteks projekt cob_nime_algus, web_nr ja mac"
   echo " nt ./cobnew eccua_optim barionet 6 00204AACD0F6"
   echo " et tekitada 00204AACD0F6/web6.cob ja kopeerida igaks juhuks ka viimane veebisetupi cgi-bin" 
   exit 1
fi


if [ ! "$4" = "" ]; then
   echo -n "cob file name is ${1}/${2}.cob, are you sure (y/n)?: "; read n
   if [ ! "$n" = "y" ]; then
        echo exiting; exit 1
   fi
fi
   
if [ $3 -gt 7 -o $3 -lt 1 ]; then
   echo "web number ${2} illegal!"
   exit 1
fi

if [ ! -d $4 ]; then
    echo "missing target directory ${4}!"
    echo -n "create directory ${4} (y/n)?:"
    read n
    if [ ! "$n" = "y" ]; then
        exit
    fi
    sudo mkdir ${4}
    echo DIRECTORY $4 DONE
   #exit 1
fi   

#if [ `echo $4 | wc -c` -eq 12 ]; then
   #$echo "mac ${4} length illegal!"
   #exit 1
#fi
#nyyd voib ka muid katalooge teha peale mac nimeliste
#mac kataloogide tegemisega tegeleb coblink

#teeme ka veebisetup failide koopiad


echo "starting scp processes from server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/${1}/"
echo -n press enter to start...; read n

if [ "$1" =  "rescue" ]; then
  echo rescue...
  sudo scp root@server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/${1}/BCL/uisystem.html /srv/www.itvilla.ee/htdocs/support/cob/${4}
else
  echo not rescue...
  sudo scp root@server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/${1}/ajax/uiappsetup*.html /srv/www.itvilla.ee/htdocs/support/cob/${4}
fi

sudo scp root@server.itvilla.ee:/srv/data/ITvilla/Barix/DevUpKits/${1}/${2}.cob ${4}/web${3}.cob
size=`ls -l ${4}/web${3}.cob | cut -d" " -f5`
echo cob file size $size
sleep 1
summ=`sum ${4}/web${3}.cob | cut -d" " -f1`
echo cob file sum $summ
#sleep 2
sudo chown witvilla ${4}/*
sudo chgrp witvilla ${4}/*
sudo ls -l ${4}/*.cob > ${4}/sizesum.txt
sudo sum ${4}/*.cob >> ${4}/sizesum.txt
#sudo cat ${4}/sizesum.txt
#echo -n "press enter to insert the update${3} command into newstate: "; read n
#CMD="insert into newstate (mac,register,value) values ('${4}','update${3}','${size},${summ}');"
#echo $CMD
#echo do it manually on server 212.47.221.86 for now...

(echo -n "$4 $1 $2 ${size},${summ} web${3} ";date) >> cobnew.out # las jaavad koik alles

#exit 0

#echo -e ".timeout 300\n${CMD}" | sqlite3 /srv/scada/sqlite/monitor
#sleep 3
#echo -e ".timeout 300\nselect * from newstate;" | sqlite3 /srv/scada/sqlite/monitor


tail cobnew.out
